name: Publish Docker Image to Docker Hub and Deploy to EC2

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #      - name: Build the Docker image
      #        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/docker_test


      - name: connect to EC2
        run: |
           sudo apt-get update
           mkdir -p ~/.ssh/
           echo "${{secrets.EC2_SSH}}" > ~/.ssh/security.pem
           chmod 400 ~/.ssh/security.pem
           ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/security.pem ec2-user@13.48.104.136
           ls -l
           curl ifconfig.me
#           pwd && cd /home/ec2-user/docker_test
#           git pull origin master
#           sudo docker-compose build
#           sudo docker-compose up
          



