name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/docker_test

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker_test
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Install AWS CLI
          run: |
            sudo apt-get update
            sudo apt-get install -y awscli

        - name: Deploy Docker image to EC2
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ${{ secrets.AWS_REGION }}
            aws configure set default.output json
    
            docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/docker_test

