#name: Publish Docker Image to Docker Hub and Deploy to EC2
#
#on:
#  push:
#    branches: ['master']
#  pull_request:
#    branches: ['master']
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/docker_test
#
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Connect to EC2
#        run: |
#          sudo apt-get update
#          mkdir -p ~/.ssh/
#          echo "${{ secrets.EC2_SSH }}" > ~/.ssh/security.pem
#          chmod 400 ~/.ssh/security.pem
#          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/security.pem ec2-user@13.48.104.136
#          ls -l
#          curl ifconfig.me
#          # pwd && cd /home/ec2-user/docker_test
#          # git pull origin master
#          # sudo docker-compose build
#          # sudo docker-compose up
name: Docker Build and EC2 Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker-compose build . --file docker-compose.yml --tag ${{ secrets.DOCKER_USERNAME }}/docker_test

    - name: Push Docker Image
      run: docker-compose push ${{ secrets.DOCKER_USERNAME }}/docker_test
#
#  deploy:
#    needs: build
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Configure SSH key
#      run: |
#        mkdir -p ~/.ssh
#        echo "${{ secrets.EC2_SSH }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#    - name: Deploy to EC2
#      run: |
#        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@13.53.97.33 << 'EOF'
#        cd /home/ec2-user/docker_test && docker pull ${{ secrets.DOCKER_USERNAME }}/docker_test
#        EOF

      
